version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  deploy:
    executor: node-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:dTbd7DeoUsp6E6cpOm1sufbJLEs3Hnglp4PTX+/2vBc"
      - run:
          name: Pull latest code from backend branch
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@15.206.123.89 "
              cd /var/www/html/MERN_Devops/backend &&
              git fetch origin backend &&
              git checkout backend &&
              git merge origin/backend --no-edit || git merge --abort &&
              git pull origin backend &&
              npm install &&
              pm2 restart 0
            "

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - backend
