version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:latest

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_backend:
    docker:
      - image: circleci/node:latest
    resource_class: medium
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:dTbd7DeoUsp6E6cpOm1sufbJLEs3Hnglp4PTX+/2vBc"
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy Files to EC2 Server
          command: |
            scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa /tmp/workspace/* ubuntu@13.201.127.64:/var/www/html/MERN_Devops/backend
      - run:
          name: Restart Backend with PM2
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa ubuntu@13.201.127.64 '
              cd /var/www/html/MERN_Devops/backend &&
              npm install --production &&
              pm2 startOrReload ecosystem.config.js --env production &&
              sudo chown -R ubuntu:ubuntu /var/www/html/MERN_Devops/backend'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install_dependencies
      - deploy_backend:
          requires:
            - install_dependencies
          filters:
            branches:
              only:
                - main
